{% set version = "0.2.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-clustimpute
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ClustImpute_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ClustImpute/ClustImpute_{{ version }}.tar.gz
  sha256: 2bcc1cb87a1d48928a6d9802b111f9158b0b947179048d4769e4039e73dd2d8a

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-clusterr
    - r-copula
    - r-dplyr
    - r-magrittr
    - r-tidyr
    - r-ggplot2
    - r-rlang
    - r-knitr
  run:
    - r-base
    - r-clusterr
    - r-copula
    - r-dplyr
    - r-magrittr
    - r-tidyr
    - r-ggplot2
    - r-rlang
    - r-knitr

test:
  commands:
    - $R -e "library('ClustImpute')"           # [not win]
    - "\"%R%\" -e \"library('ClustImpute')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=ClustImpute
  license: GPL-3.0-only
  summary: This k-means algorithm is able to cluster data with missing values and as a by-product completes the data set. The implementation can deal with missing values in multiple variables and is computationally efficient since it iteratively uses the current cluster assignment to define a plausible distribution for missing value imputation. Weights are used to shrink early random draws for missing values (i.e., draws based on the cluster assignments after few iterations) towards the global mean of each feature. This shrinkage slowly fades out after a fixed number of iterations to reflect the increasing credibility of cluster assignments. See the vignette for details.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - mfansler

# Package: ClustImpute
# Type: Package
# Title: K-means clustering with build-in missing data imputation
# Version: {{ version }}
# Author: Oliver Pfaffel
# Maintainer: Oliver Pfaffel <opfaffel@gmail.com>
# Description: This k-means algorithm is able to cluster data with missing values and as a by-product completes the data set. The implementation can deal with missing values in multiple variables and is computationally efficient since it iteratively uses the current cluster assignment to define a plausible distribution for missing value imputation. Weights are used to shrink early random draws for missing values (i.e., draws based on the cluster assignments after few iterations) towards the global mean of each feature. This shrinkage slowly fades out after a fixed number of iterations to reflect the increasing credibility of cluster assignments. See the vignette for details.
# License: GPL-3
# Encoding: UTF-8
# LazyData: true
# Imports: ClusterR, copula, dplyr, magrittr, tidyr, ggplot2, rlang, knitr
# Suggests: ggExtra, rmarkdown, testthat (>= 2.1.0), Hmisc, tictoc, spelling, corrplot, covr
# VignetteBuilder: knitr
# RoxygenNote: 7.1.0
# Language: en-US
# NeedsCompilation: no
# Packaged: 2021-03-20; opfaf
# Repository: CRAN
# Date/Publication: 2021-03-20
